---
title: "Data Maturity Model"
params:
  answer_1: NA
  answer_2: NA
  answer_3: NA
  answer_4: NA
  answer_5: NA
  answer_6: NA
  answer_7: NA
  name: NA
  printcode: no
  team: NA
output:
  html_document: default
  pdf_document: default
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = params$printcode, comment = NA)
library(dplyr)
library(plotly)
```

Name
 ```{r}
 cat(params$name)
 ```
Team
 ```{r}
cat(params$team)
 ```

Data Management Awareness
 ```{r}
 cat(params$answer_1)
 ```
Data Management Governance
 ```{r}
 cat(params$answer_2)
 ```
Metadata
 ```{r}
 cat(params$answer_3)
 ```
Storage and Security
 ```{r}
 cat(params$answer_4)
 ```
Retention and Versioning
 ```{r}
 cat(params$answer_5)
 ```
Data Sharing 
 ```{r}
 cat(params$answer_6)
 ```
Data Processing
 ```{r}
 cat(params$answer_7)
 ```
 
 Chart
 ```{r echo = FALSE, warnings = FALSE}

       plotly::plot_ly(
            type = "scatterpolar",
            mode = "lines",
            r = c(strtoi(substr(params$answer_1[1], 7, 7)), 
                  strtoi(substr(params$answer_2[1], 7, 7)), 
                  strtoi(substr(params$answer_3[1], 7, 7)), 
                  strtoi(substr(params$answer_4[1], 7, 7)), 
                  strtoi(substr(params$answer_5[1], 7, 7)), 
                  strtoi(substr(params$answer_6[1], 7, 7)), 
                  strtoi(substr(params$answer_7[1], 7, 7))
                  ),
            theta = c("Data Management Awareness", 
                      "Data Management Governance", 
                      "Metadata", 
                      "Storage and Security", 
                      "Retention and Versioning", 
                      "Data Sharing", 
                      "Data Processing"),
            fill = "toself"
        ) %>% layout(polar = list(radialaxis = list(visible = T,
        range = c(0,5)
                        )
                ),
                showlegend = F
            )

 ```